### ISSUE TITLE
NDK support

### ISSUE THREAD

**Issue by qpaolo** [SimPrints/libAFIS#56]
Does this work with Android NDK?

**Comment by TristramN** [comment]
There shouldn't be any dependancies it requires that would stop it from working with the NDK. In fact our first major use case is the NDK so when we have it up and running specifically we'll have an "NDK: getting started" guide.

**Comment by qpaolo** [comment]
Can I ask when the basic functionalities (like matcher...) are done?

**Comment by TristramN** [comment]
No hard dates on that unfortunately. We are currently using a different matcher so our priority is extraction for now. The work on the project will ramp up in January, but matcher is last on the list so it could be 6+ months.

**Comment by qpaolo** [comment]
Thanks for response :)
Can you tell me what matcher are you using please? Is it open source?
To be honest, I'm using another extraction library :(

**Comment by TristramN** [comment]
I hope you are using another extracter since this one isn't completed yet!
